/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo */

#ifndef _Included_demo
#define _Included_demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo
 * Method:    createdemo
 * Signature: ()Ldemo;
 */
JNIEXPORT jobject JNICALL Java_demo_createdemo
  (JNIEnv *, jclass);

/*
 * Class:     demo
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
