/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyThread */


#ifndef _Included_MyThread
#define _Included_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyThread
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyThread_init
  (JNIEnv *, jclass);

/*
 * Class:     MyThread
 * Method:    start
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_MyThread_start
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     MyThread
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyThread_free
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
